// Generated by gencpp from file notice/device_status.msg
// DO NOT EDIT!


#ifndef NOTICE_MESSAGE_DEVICE_STATUS_H
#define NOTICE_MESSAGE_DEVICE_STATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace notice
{
template <class ContainerAllocator>
struct device_status_
{
  typedef device_status_<ContainerAllocator> Type;

  device_status_()
    : speed(0.0)
    , battery(0)
    , millage(0)
    , emergencyStop(false)
    , charge(false)  {
    }
  device_status_(const ContainerAllocator& _alloc)
    : speed(0.0)
    , battery(0)
    , millage(0)
    , emergencyStop(false)
    , charge(false)  {
  (void)_alloc;
    }



   typedef float _speed_type;
  _speed_type speed;

   typedef int8_t _battery_type;
  _battery_type battery;

   typedef int64_t _millage_type;
  _millage_type millage;

   typedef uint8_t _emergencyStop_type;
  _emergencyStop_type emergencyStop;

   typedef uint8_t _charge_type;
  _charge_type charge;




  typedef boost::shared_ptr< ::notice::device_status_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::notice::device_status_<ContainerAllocator> const> ConstPtr;

}; // struct device_status_

typedef ::notice::device_status_<std::allocator<void> > device_status;

typedef boost::shared_ptr< ::notice::device_status > device_statusPtr;
typedef boost::shared_ptr< ::notice::device_status const> device_statusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::notice::device_status_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::notice::device_status_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace notice

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'notice': ['/home/jimmy/github/MyRepo/testbot_ws/src/notice/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::notice::device_status_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::notice::device_status_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::notice::device_status_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::notice::device_status_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::notice::device_status_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::notice::device_status_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::notice::device_status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1aeaee6c26e1c6beeee5f561cec487dc";
  }

  static const char* value(const ::notice::device_status_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1aeaee6c26e1c6beULL;
  static const uint64_t static_value2 = 0xeee5f561cec487dcULL;
};

template<class ContainerAllocator>
struct DataType< ::notice::device_status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "notice/device_status";
  }

  static const char* value(const ::notice::device_status_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::notice::device_status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 speed\n\
int8 battery\n\
int64 millage\n\
bool emergencyStop\n\
bool charge\n\
";
  }

  static const char* value(const ::notice::device_status_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::notice::device_status_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.speed);
      stream.next(m.battery);
      stream.next(m.millage);
      stream.next(m.emergencyStop);
      stream.next(m.charge);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct device_status_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::notice::device_status_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::notice::device_status_<ContainerAllocator>& v)
  {
    s << indent << "speed: ";
    Printer<float>::stream(s, indent + "  ", v.speed);
    s << indent << "battery: ";
    Printer<int8_t>::stream(s, indent + "  ", v.battery);
    s << indent << "millage: ";
    Printer<int64_t>::stream(s, indent + "  ", v.millage);
    s << indent << "emergencyStop: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.emergencyStop);
    s << indent << "charge: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.charge);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NOTICE_MESSAGE_DEVICE_STATUS_H
