// Generated by gencpp from file notice/system_health_status.msg
// DO NOT EDIT!


#ifndef NOTICE_MESSAGE_SYSTEM_HEALTH_STATUS_H
#define NOTICE_MESSAGE_SYSTEM_HEALTH_STATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace notice
{
template <class ContainerAllocator>
struct system_health_status_
{
  typedef system_health_status_<ContainerAllocator> Type;

  system_health_status_()
    : laserConnection(false)
    , SonarConnection()
    , MCUConnection(false)  {
      SonarConnection.assign(0);
  }
  system_health_status_(const ContainerAllocator& _alloc)
    : laserConnection(false)
    , SonarConnection()
    , MCUConnection(false)  {
  (void)_alloc;
      SonarConnection.assign(0);
  }



   typedef uint8_t _laserConnection_type;
  _laserConnection_type laserConnection;

   typedef boost::array<int16_t, 8>  _SonarConnection_type;
  _SonarConnection_type SonarConnection;

   typedef uint8_t _MCUConnection_type;
  _MCUConnection_type MCUConnection;




  typedef boost::shared_ptr< ::notice::system_health_status_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::notice::system_health_status_<ContainerAllocator> const> ConstPtr;

}; // struct system_health_status_

typedef ::notice::system_health_status_<std::allocator<void> > system_health_status;

typedef boost::shared_ptr< ::notice::system_health_status > system_health_statusPtr;
typedef boost::shared_ptr< ::notice::system_health_status const> system_health_statusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::notice::system_health_status_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::notice::system_health_status_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace notice

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'notice': ['/home/jimmy/github/MyRepo/testbot_ws/src/notice/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::notice::system_health_status_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::notice::system_health_status_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::notice::system_health_status_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::notice::system_health_status_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::notice::system_health_status_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::notice::system_health_status_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::notice::system_health_status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "597f5922ff244034653f9d597018a242";
  }

  static const char* value(const ::notice::system_health_status_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x597f5922ff244034ULL;
  static const uint64_t static_value2 = 0x653f9d597018a242ULL;
};

template<class ContainerAllocator>
struct DataType< ::notice::system_health_status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "notice/system_health_status";
  }

  static const char* value(const ::notice::system_health_status_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::notice::system_health_status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool laserConnection\n\
int16[8] SonarConnection\n\
bool MCUConnection\n\
";
  }

  static const char* value(const ::notice::system_health_status_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::notice::system_health_status_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.laserConnection);
      stream.next(m.SonarConnection);
      stream.next(m.MCUConnection);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct system_health_status_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::notice::system_health_status_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::notice::system_health_status_<ContainerAllocator>& v)
  {
    s << indent << "laserConnection: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.laserConnection);
    s << indent << "SonarConnection[]" << std::endl;
    for (size_t i = 0; i < v.SonarConnection.size(); ++i)
    {
      s << indent << "  SonarConnection[" << i << "]: ";
      Printer<int16_t>::stream(s, indent + "  ", v.SonarConnection[i]);
    }
    s << indent << "MCUConnection: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.MCUConnection);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NOTICE_MESSAGE_SYSTEM_HEALTH_STATUS_H
