# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from notice/device_status.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class device_status(genpy.Message):
  _md5sum = "1aeaee6c26e1c6beeee5f561cec487dc"
  _type = "notice/device_status"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float32 speed
int8 battery
int64 millage
bool emergencyStop
bool charge"""
  __slots__ = ['speed','battery','millage','emergencyStop','charge']
  _slot_types = ['float32','int8','int64','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       speed,battery,millage,emergencyStop,charge

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(device_status, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.speed is None:
        self.speed = 0.
      if self.battery is None:
        self.battery = 0
      if self.millage is None:
        self.millage = 0
      if self.emergencyStop is None:
        self.emergencyStop = False
      if self.charge is None:
        self.charge = False
    else:
      self.speed = 0.
      self.battery = 0
      self.millage = 0
      self.emergencyStop = False
      self.charge = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_fbq2B.pack(_x.speed, _x.battery, _x.millage, _x.emergencyStop, _x.charge))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 15
      (_x.speed, _x.battery, _x.millage, _x.emergencyStop, _x.charge,) = _struct_fbq2B.unpack(str[start:end])
      self.emergencyStop = bool(self.emergencyStop)
      self.charge = bool(self.charge)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_fbq2B.pack(_x.speed, _x.battery, _x.millage, _x.emergencyStop, _x.charge))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 15
      (_x.speed, _x.battery, _x.millage, _x.emergencyStop, _x.charge,) = _struct_fbq2B.unpack(str[start:end])
      self.emergencyStop = bool(self.emergencyStop)
      self.charge = bool(self.charge)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_fbq2B = struct.Struct("<fbq2B")
