# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from notice/nav_status.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import std_msgs.msg

class nav_status(genpy.Message):
  _md5sum = "13261ca54d3655f9b32e5b0b779d7089"
  _type = "notice/nav_status"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """Header head
string noticeTypeLevel
string noticeType
string noticeDataFields
geometry_msgs/Pose2D ExpectedPosition
geometry_msgs/Pose worldPosition


  
  



================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: geometry_msgs/Pose2D
# This expresses a position and orientation on a 2D manifold.

float64 x
float64 y
float64 theta
================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of postion and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w
"""
  __slots__ = ['head','noticeTypeLevel','noticeType','noticeDataFields','ExpectedPosition','worldPosition']
  _slot_types = ['std_msgs/Header','string','string','string','geometry_msgs/Pose2D','geometry_msgs/Pose']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       head,noticeTypeLevel,noticeType,noticeDataFields,ExpectedPosition,worldPosition

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(nav_status, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.head is None:
        self.head = std_msgs.msg.Header()
      if self.noticeTypeLevel is None:
        self.noticeTypeLevel = ''
      if self.noticeType is None:
        self.noticeType = ''
      if self.noticeDataFields is None:
        self.noticeDataFields = ''
      if self.ExpectedPosition is None:
        self.ExpectedPosition = geometry_msgs.msg.Pose2D()
      if self.worldPosition is None:
        self.worldPosition = geometry_msgs.msg.Pose()
    else:
      self.head = std_msgs.msg.Header()
      self.noticeTypeLevel = ''
      self.noticeType = ''
      self.noticeDataFields = ''
      self.ExpectedPosition = geometry_msgs.msg.Pose2D()
      self.worldPosition = geometry_msgs.msg.Pose()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.head.seq, _x.head.stamp.secs, _x.head.stamp.nsecs))
      _x = self.head.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.noticeTypeLevel
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.noticeType
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.noticeDataFields
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_10d.pack(_x.ExpectedPosition.x, _x.ExpectedPosition.y, _x.ExpectedPosition.theta, _x.worldPosition.position.x, _x.worldPosition.position.y, _x.worldPosition.position.z, _x.worldPosition.orientation.x, _x.worldPosition.orientation.y, _x.worldPosition.orientation.z, _x.worldPosition.orientation.w))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.head is None:
        self.head = std_msgs.msg.Header()
      if self.ExpectedPosition is None:
        self.ExpectedPosition = geometry_msgs.msg.Pose2D()
      if self.worldPosition is None:
        self.worldPosition = geometry_msgs.msg.Pose()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.head.seq, _x.head.stamp.secs, _x.head.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.head.frame_id = str[start:end].decode('utf-8')
      else:
        self.head.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.noticeTypeLevel = str[start:end].decode('utf-8')
      else:
        self.noticeTypeLevel = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.noticeType = str[start:end].decode('utf-8')
      else:
        self.noticeType = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.noticeDataFields = str[start:end].decode('utf-8')
      else:
        self.noticeDataFields = str[start:end]
      _x = self
      start = end
      end += 80
      (_x.ExpectedPosition.x, _x.ExpectedPosition.y, _x.ExpectedPosition.theta, _x.worldPosition.position.x, _x.worldPosition.position.y, _x.worldPosition.position.z, _x.worldPosition.orientation.x, _x.worldPosition.orientation.y, _x.worldPosition.orientation.z, _x.worldPosition.orientation.w,) = _struct_10d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.head.seq, _x.head.stamp.secs, _x.head.stamp.nsecs))
      _x = self.head.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.noticeTypeLevel
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.noticeType
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.noticeDataFields
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_10d.pack(_x.ExpectedPosition.x, _x.ExpectedPosition.y, _x.ExpectedPosition.theta, _x.worldPosition.position.x, _x.worldPosition.position.y, _x.worldPosition.position.z, _x.worldPosition.orientation.x, _x.worldPosition.orientation.y, _x.worldPosition.orientation.z, _x.worldPosition.orientation.w))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.head is None:
        self.head = std_msgs.msg.Header()
      if self.ExpectedPosition is None:
        self.ExpectedPosition = geometry_msgs.msg.Pose2D()
      if self.worldPosition is None:
        self.worldPosition = geometry_msgs.msg.Pose()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.head.seq, _x.head.stamp.secs, _x.head.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.head.frame_id = str[start:end].decode('utf-8')
      else:
        self.head.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.noticeTypeLevel = str[start:end].decode('utf-8')
      else:
        self.noticeTypeLevel = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.noticeType = str[start:end].decode('utf-8')
      else:
        self.noticeType = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.noticeDataFields = str[start:end].decode('utf-8')
      else:
        self.noticeDataFields = str[start:end]
      _x = self
      start = end
      end += 80
      (_x.ExpectedPosition.x, _x.ExpectedPosition.y, _x.ExpectedPosition.theta, _x.worldPosition.position.x, _x.worldPosition.position.y, _x.worldPosition.position.z, _x.worldPosition.orientation.x, _x.worldPosition.orientation.y, _x.worldPosition.orientation.z, _x.worldPosition.orientation.w,) = _struct_10d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_3I = struct.Struct("<3I")
_struct_10d = struct.Struct("<10d")
